CREATE TABLE IF NOT EXISTS risk_cases (
  case_id VARCHAR(64) PRIMARY KEY,
  merchant_id VARCHAR(64) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  risk_category VARCHAR(128) NOT NULL,
  case_status VARCHAR(64) NOT NULL DEFAULT 'pending_review',
  risk_score DECIMAL(6,4) NOT NULL DEFAULT 0,
  evidence_json JSON NOT NULL,
  triggered_by VARCHAR(128) NOT NULL DEFAULT '',
  occurred_at_ms BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
