CREATE TABLE IF NOT EXISTS risk_cases (
  case_id VARCHAR(64) PRIMARY KEY,
  merchant_id VARCHAR(64) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  risk_category VARCHAR(128) NOT NULL,
  case_status VARCHAR(64) NOT NULL DEFAULT 'pending_review',
  risk_score DECIMAL(6,4) NOT NULL DEFAULT 0,
  evidence_json JSON NOT NULL,
  triggered_by VARCHAR(128) NOT NULL DEFAULT '',
  occurred_at_ms BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS risk_ingest_idempotency (
  idempotency_key VARCHAR(128) PRIMARY KEY,
  case_id VARCHAR(64) NOT NULL,
  replay_count INT NOT NULL DEFAULT 0,
  first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_risk_ingest_case_id (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS risk_outbox_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  case_id VARCHAR(64) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  payload_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  publish_attempts INT NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_error VARCHAR(255) NOT NULL DEFAULT '',
  locked_at TIMESTAMP NULL DEFAULT NULL,
  published_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_risk_outbox_dispatch (status, next_attempt_at),
  KEY idx_risk_outbox_case_id (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS risk_audit_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  case_id VARCHAR(64) NOT NULL,
  action VARCHAR(64) NOT NULL,
  detail_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_risk_audit_case_created (case_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
